### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jhampt** [Zedstar16/OnlineTime#1]
make a pull request on scorehud for support for this plugin?

**Comment by Zedstar16** [comment]
Possibly,
should it be total time, session time or both

**Comment by jhampt** [comment]
Both?

**Comment by Zedstar16** [comment]
OnlineTime addon is done, it should appear in jack's addon repository soon,
The tags are {total_time} and {session_time}

While jack adds it to his repo, download the onlinetime addon [here](http://www.mediafire.com/file/lw4sgh979pgbcxe/OnlineTimeAddon.php/file)
