### ISSUE TITLE
running "ot" command will crash server

### ISSUE THREAD

**Issue by SageBrushes** [Zedstar16/OnlineTime#10]
On a new install, simply writing "ot" and pressing enter will crash the server.

https://crash.pmmp.io/view/2709311

**Comment by Zedstar16** [comment]
Thanks for creating the issue.
I can see that it is caused from running the command inside console.
The issue should not happen when the command is run by a player in game.
I'll work on a patch

**Comment by Zedstar16** [comment]
Fixed in commit [#4df9f5d](https://github.com/Zedstar16/OnlineTime/commit/4df9f5d9accb9491d6d88025b0f2e7928a5cec13)
