### ISSUE TITLE
hi!

### ISSUE THREAD

**Issue by callumrawlinson** [Zedstar16/OnlineTime#19]
Would this be able to tell if a player is currently online

**Comment by callumrawlinson** [comment]
@Zedstar16 any thoughts?

**Comment by Zedstar16** [comment]
Using /ot session (username)
should tell you if the player is online

**Comment by callumrawlinson** [comment]
ok thank you! is there an api i could use aswell or not? its fine if not

**Comment by callumrawlinson** [comment]
so if a player is online and they have permission online.list or something it would show up

**Comment by callumrawlinson** [comment]
@Zedstar16

**Comment by Zedstar16** [comment]
You can use built in pocketmine functions for this.
Simply filter the online player list by users that have that permission

**Comment by callumrawlinson** [comment]
im not sure how though. i have never worked with items like this i usually just do some other stuff

**Comment by Zedstar16** [comment]
> ok thank you! is there an api i could use aswell or not? its fine if not

Regarding this, yes there is an internal API

get the onlinetime base via 

```php
$ot = ....pluginManager()->getPlugin("OnlineTime");
```

Access to the db (SQlite.php) class in the plugin is public, so you can do 
```php
$ot->db->AnyMethodInSqlite.php
```

**Comment by callumrawlinson** [comment]
ok thank you

**Comment by Zedstar16** [comment]
> im not sure how though. i have never worked with items like this i usually just do some other stuff

This is more a support request for the pmmp API than onlinetime, but if you want to get a list of players online with a certain permission

Either get the list of players online the server `$this->getServer()->getOnlinePlayers()`
foreach that and check if the player has a certain permission.

Or use `array_filter()` to filter the player list and return `player->hasPermission("perm")` in the callback function

**Comment by callumrawlinson** [comment]
ok thank you! that has helped alot. how would i send the list though.

**Comment by Zedstar16** [comment]
> ok thank you! that has helped alot. how would i send the list though.

If you use foreach you could put the name of the player in an array, then `implode()` the array to get a string list of players

**Comment by callumrawlinson** [comment]
im not sure. but thank you for your help! :)
