### ISSUE TITLE
Addon?? 

### ISSUE THREAD

**Issue by ghost** [Zedstar16/OnlineTime#2]
Can you make an Addon for ScoreHud please

**Comment by Zedstar16** [comment]
Addon for score hud will be coming soon

**Comment by ghost** [comment]
thanks

**Comment by Zedstar16** [comment]
OnlineTime addon is done, it should appear in jack's addon repository soon,
The tags are {total_time} and {session_time}

While jack adds it to his repo, download the onlinetime addon [here](http://www.mediafire.com/file/lw4sgh979pgbcxe/OnlineTimeAddon.php/file)
