### ISSUE TITLE
Active Time vs Idle Time - Enhancement

### ISSUE THREAD

**Issue by ver24436** [Zedstar16/OnlineTime#5]
I'm not sure how difficult it would be but I was wondering if you would consider adding tracking of active time vs idle time.  It'd be nice to be able to see how much time a player is idle(afk) vs how much time they spent actively engaged in the server, chatting moving, placing or removing block.

**Comment by Zedstar16** [comment]
Sure, i'll probably get round to doing that after i finish my exams, in just under a month, with all the other todo features

**Comment by Zedstar16** [comment]
Added a branch that stops counting online time for a player if they are AFK for more than 5 mins
[Dev Branch](https://github.com/Zedstar16/OnlineTime/tree/Dev)

**Comment by Zedstar16** [comment]
only active time will be counted, inactive time will simply be disregarded
