### ISSUE TITLE
Issues...

### ISSUE THREAD

**Issue by isoz** [Zedstar16/OnlineTime#6]
![image](https://user-images.githubusercontent.com/6126350/58749460-872b0500-847e-11e9-95ec-50c5c7272763.png)

![image](https://user-images.githubusercontent.com/6126350/58749462-8eeaa980-847e-11e9-8f27-abb1db702bcd.png)

Doesn't seem to be displaying the times correctly for most users, some are correct like my name but most aren't.

Those UUID characters look off, not sure if it's suppose to be that way, could be where the fault is.

**Comment by isoz** [comment]
For some reason it sort of "fixed" itself? 
![image](https://user-images.githubusercontent.com/6126350/58754159-769c7e00-84c2-11e9-8ab8-ffa2e642a55e.png)

But it's still wrong, those plays dont have 0 hours and 0 seconds.

**Comment by Zedstar16** [comment]
Thanks for creating the issue, i will look into it further.
Could you send the players.db file for the plugin on your server?

**Comment by isoz** [comment]
Here:
[players.zip](https://github.com/Zedstar16/OnlineTime/files/3248266/players.zip)

I said it "fixed" itself but it didn't, results end up going all over the place again, very confusing.

**Comment by Zedstar16** [comment]
The ordering of top times appears correct,
It appears to be an issue with the total time function,
Will be fixing shortly

**Comment by Zedstar16** [comment]
Issue with incorrect top values and mixed case player names patched in
commit [#1a6a71a](https://github.com/Zedstar16/OnlineTime)
