### ISSUE TITLE
Here a error code

### ISSUE THREAD

**Issue by note3crafter** [Zedstar16/OnlineTime#9]
PocketMine-MP Crash Dump Tue Jul 9 11:49:29 CEST 2019

Error: SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly database
File: plugins/OnlineTime.phar/src/Zedstar16/OnlineTime/database/SQLite
Line: 119
Type: ErrorException

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: OnlineTime v1.2

Code:

Backtrace:
#0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[89] SQLite3Stmt::execute(): Unable to execute statement: attempt to write a readonly, string[91] phar:///home/minecraft/plugins/OnlineTime.phar/src/Zedstar16/OnlineTime/database, integer 119, array[5])
#1 plugins/OnlineTime.phar/src/Zedstar16/OnlineTime/database/SQLite(119): SQLite3Stmt->execute()
#2 plugins/OnlineTime.phar/src/Zedstar16/OnlineTime/Main(44): Zedstar16\OnlineTime\database\SQLite->setRawTime(object pocketmine\Player, integer 34890)
#3 src/pocketmine/plugin/MethodEventExecutor(38): Zedstar16\OnlineTime\Main->onQuit(object pocketmine\event\player\PlayerQuitEvent)
#4 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(object Zedstar16\OnlineTime\Main, object pocketmine\event\player\PlayerQuitEvent)
#5 src/pocketmine/event/Event(99): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent)
#6 src/pocketmine/Player(3496): pocketmine\event\Event->call()
#7 src/pocketmine/network/mcpe/RakLibInterface(122): pocketmine\Player->close(object pocketmine\lang\TranslationContainer, string[7] timeout)
#8 vendor/pocketmine/raklib/src/server/ServerHandler(131): pocketmine\network\mcpe\RakLibInterface->closeSession(string[19] 91.96.167.155 40570, string[7] timeout)
#9 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
#10 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
#11 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
#12 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
#13 src/pocketmine/Server(2348): pocketmine\snooze\SleeperHandler->sleepUntil(double 1562665769.1201)
#14 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
#15 src/pocketmine/Server(1784): pocketmine\Server->start()
#16 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#17 (1): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

**Comment by Zedstar16** [comment]
Does this error occur every time a player leaves the game or has it just happened this once?

Also, does the plugin have read & write file permissions to the folder that the players.db file is stored in, either plugins_data/OnlineTime or plugins/OnlineTime - depending on your PMMP version
